---
title: "MMUS Finemap"
output: BiocStyle::html_document
author: "Matthias Munz"
vignette: >
    %\VignetteIndexEntry{Finemapping}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Introduction
This **R** package provides an in-silico method for finemapping of genetic regions in mice.


# Installation
```{r setup, eval=FALSE}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("mmus")
```

or 

```{r eval=FALSE}
devtools::install_github('matmu/mmus', build_vignettes = TRUE)
```

# Loading package
```{r}
library(mmus)
```

# Example function calls
Call mmusfinemap to finemap a specific region
```{r}
res = mmusfinemap(chr=c("chr7"),strain1=c("C57BL_6J","C57L_J","CBA_J","NZB_B1NJ"),
                   strain2=c("C3H_HEJ","MOLF_EiJ","NZW_LacJ","WSB_EiJ","SPRET_EiJ"),
                  impact=c("HIGH", "MODERATE", "LOW"))

res[1:10,]
```

Annotate consequences and genes
```{r eval=FALSE}
cons = annotate_consequences(res, "mouse")
```

# Output of Session Info
The output of ```sessionInfo()``` on the system
on which this document was compiled:
```{r}
sessionInfo()
```
