---
title: "MMUS Prio"
output: BiocStyle::html_document
author: "Matthias Munz"
vignette: >
    %\VignetteIndexEntry{Prioritization}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Introduction
This **R** package provides an in-silico method finemapping of genetic regions in mice.


# Installation
```{r setup, eval=FALSE}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("mmus")
```

# Loading package
```{r}
library(mmus)
```

# Example function calls
```{r}
# Call mmusprio to prioritize additional mouse strains for a given region
df = mmusprio("chr1", start=5000000, end=6000000, strain1="C57BL_6J", strain2="AKR_J")

# Generate plots
plots = vis_reduction_factors(df$genotypes, df$reduction, 2)
plots[[1]]
plots[[2]]
```

# Output of Session Info
The output of ```sessionInfo()``` on the system
on which this document was compiled:
```{r}
sessionInfo()
```
